### ISSUE TITLE
We should change the license information

### ISSUE THREAD

**Issue by jforge** [ImmoweltGroup/ansible-modules-immowelt#1]
On the Axel Springer Open Source Development Day we reached an agreement about valid licenses in AS subsidiary companies' Open Source projects.

As a result our Immowelt OSS project should be licenses with either MIT or Apache 2.0 License.

This should be changed by the primary committer, otherwise we have to discuss in detail, why this project should have a GPL3 license.

**Comment by denniskribl** [comment]
From the official Ansible [documentation](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_in_groups.html):

> All modules shipped with Ansible must be done so under the GPLv3 license. Files under the lib/ansible/module_utils/ directory should be done so under the BSD license.


For further publishing we will be forced to use the GPL3 license. Otherwise we won't be able to create an official pull request for this module.

**Comment by jforge** [comment]
The stated reason seems to be very acceptable ;-)
